### PR TITLE
-Fix : PWA 추가, modal 처음 렌더되게 

### PR DESCRIPTION
**Pull request by rnujhgd**

### CODE REVIEW

**Review by CMU02 — APPROVED** [review]
LGTM

**Review by chansooda — APPROVED** [review]
good~

**Review by kgw-coding — APPROVED** [review]
nice

**Review by choisiheon — APPROVED** [review]
good

**Review by kgw-coding — APPROVED** [review]
good

**Review by CMU02 — APPROVED** [review]

**Review by choisiheon — APPROVED** [review]
good

**Pull request merged**
